# Generated by Django 5.2 on 2025-06-29 02:08

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='Новый чат', max_length=255, null=True)),
                ('gpt_enabled', models.BooleanField(default=True)),
                ('stage', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=chat.models.upload_docs_file)),
            ],
        ),
        migrations.CreateModel(
            name='FaissFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=chat.models.upload_faiss_file)),
            ],
        ),
        migrations.CreateModel(
            name='Func',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(blank=True, choices=[('1|TELEGRAM', 'Telegram - Открытая линия'), ('whatsapp', 'whatsapp'), ('telegram_bot', 'telegram_bot'), ('avito', 'avito'), ('vk', 'vk'), ('instagram', 'instagram')], max_length=40, null=True)),
                ('first_message', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=40, null=True)),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(default='integer', max_length=255)),
                ('description', models.TextField()),
                ('required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RagFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=chat.models.upload_rag_file)),
            ],
        ),
    ]
