# Generated by Django 5.2 on 2025-06-29 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('lead_id', models.CharField(max_length=100, unique=True)),
                ('dialog_id', models.CharField(max_length=100)),
                ('crm', models.CharField(choices=[('bitrix', 'bitrix'), ('amo', 'amo')], max_length=20)),
                ('lead_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, null=True)),
                ('segment', models.CharField(blank=True, choices=[('Новый', 'Новый'), ('Горячий', 'Горячий'), ('Тёплый', 'Тёплый'), ('Холодный', 'Холодный'), ('Купил', 'Купил'), ('Не купил', 'Не купил')], max_length=32, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
